proxies:
  - name: local
    type: http
    server: 127.0.0.1
    port: 7890

rules:
  - RULE-SET,google,local
  - DOMAIN-SUFFIX,example.com,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,::/127,DIRECT
  - MATCH,local

rule-providers:
  google:
    type: http
    behavior: domain
    format: yaml
    url: https://example.com/google.yaml
    interval: 86400
